### ISSUE TITLE
Bundle.js in index.html

### ISSUE THREAD

**Issue by danieladugyan** [psvenk/classroom-export-viewer#2] opened 2020-06-09 09:36 UTC
The script file that appears in `dist/` after building is called `script.js` instead of `bundle.js`, see [index.html](https://github.com/psvenk/classroom-export-viewer/blob/master/src/index.html#L64). Unsure if that's the case for everyone, I'm running node 8.10.0/npm 3.5.2 on WSL.

**Comment by psvenk** [comment] 2020-06-09 15:49
Thank you for pointing this out. `bundle.js` was the file name used prior to 889e6b16e2 (because I was using Rollup), and I forgot to change the `<script>` tag in the HTML to point to `script.js`. This should be fixed in 6887114c13; does it work as intended on your end?

Also, I'm happy to see that more people than me are finding Classroom Export Viewer useful!

By the way, your versions of Node and NPM are out of date; Node.js 8.x reached end of life [at the end of 2019](https://en.wikipedia.org/wiki/Node.js#Releases). I don't know if this would affect how the build scripts work because I have only tested them on my machine (and Arch Linux generally has the latest stable version of everything). You can get node 10.x by upgrading WSL to Ubuntu 20.04 LTS, but I would recommend using [nodesource's package repository](https://github.com/nodesource/distributions/blob/master/README.md) ([as recommended on the Node.js website](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions-enterprise-linux-fedora-and-snap-packages)) or something like [nvm](https://github.com/nvm-sh/nvm) if you want a more recent (14.x) version of Node.

**Closed as completed** 2020-06-09 16:04 UTC
